---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: writer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tyagipurshottam/argued.git
    targetRevision: HEAD
    path: homework/writer
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
      allowEmpty: false 
    # syncOptions: 
    #   - Validate=true
    #   - CreateNamespace=false
    #   - PrunePropagationPolicy=foreground
    #   - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reader
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tyagipurshottam/argued.git
    targetRevision: HEAD
    path: homework/reader
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
      allowEmpty: false 
    # syncOptions: 
    #   - Validate=true
    #   - CreateNamespace=false
    #   - PrunePropagationPolicy=foreground
    #   - PruneLast=true